### ISSUE TITLE
Additional 'Lezing loopt tot' date picker

### ISSUE THREAD

**Issue by ghost** [RMTweedeKamer/presidium-manager#11]
Currently, either the submitter or the Presidium has to manually add the line of `Lezing loopt tot...` in the proposal's text.

I propose adding a date picker between _postdatum_ and _stemdatum_, which also automatically picks the date three days from _postdatum_.

**Comment by th8** [comment]
This has been implemented as of e2ce34b25616f47075b40023ec1134086559d222
