### ISSUE TITLE
MRvS

### ISSUE THREAD

**Issue by 123ricardo210** [RMTweedeKamer/presidium-manager#19]
De MRvS de optie geven om gelijktijdig met het posten van een kamerstuk (wetsvoorstel, besluit, eventueel een ander kamerstuk) door de bot een comment te laten plaatsen met daarin het advies dat eerder ergens is ingevoerd.

**Comment by th8** [comment]
Has been implemented as of 91bc5d5e55a0a240725a8a480ff6d2cbc2a31a5f
