### ISSUE TITLE
Mogelijkheid tot automatische feedback vanuit MRvS

### ISSUE THREAD

**Issue by 123ricardo210** [RMTweedeKamer/presidium-manager#21]
Kamerstukken waar een advies voor is opgeslagen via reddit terugsturen naar indiener, indien dit wordt aangevinkt (zodat het daarvoor eventueel nog kan worden doorgelezen of het eventueel handmatig op discord kan worden gedaan)

**Comment by th8** [comment]
Implemented as of 2f1b816a7b542eea52af72937db2f05bfe7d192e
