### ISSUE TITLE
Ability to post voting

### ISSUE THREAD

**Issue by ghost** [RMTweedeKamer/presidium-manager#3]
**Describe the solution you'd like**
By adding an additional field for a voting date, which automatically should post a vote submission to the subreddit on the specific date.

**Comment by th8** [comment]
Posting of votes has been implemented and seems to be working as intended now. 

Workflow with regards to amendments and other reasons to delay voting is sub-optimal as one would need to keep rescheduling the votedate to push back legislation that need to not be voted on. Another solution is desirable.

@PaddoWonderland can you discuss possible solutions with the Presidium in regards with what would be a desirable solution?

**Comment by ghost** [comment]
One such solution could be a checkbox that marks the proposal for delay, in which the proposal would not be submitted for voting until the checkbox has been unchecked. Rescheduling must be mandatory afterwards. The proposal for legislation remains in the queue until it has been unchecked and rescheduled.

**Comment by th8** [comment]
Delaying votes for legislation has been implemented
